services:
  ia_setup:
    hostname:         ia_setup.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_setup:latest
        -           ia_setup:latest
        - innovanon/ia_setup
        -           ia_setup
    image:            innovanon/ia_setup
    restart:          no
    logging:
      driver:         syslog   
