on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: apt update
    - run: apt upgrade -y
    - run: apt install python3-dev
    - run: pip install -r requirements.txt
    - run: pip install .
    # TODO pyinstaller
    # TODO deploy src
    # TODO deploy whl
    - run: pip install tox
    - run: tox -e py
    - run: pip install twine
    - run: twine upload dist/
