on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - run: sudo apt update
    - run: sudo apt upgrade -y

    - uses: actions/setup-python@v5
    - run: sudo apt install python3-dev

    - run: pip install --upgrade --no-deps -r requirements.txt
    - run: pip install --upgrade --no-deps .

    #- run: pip install tox
    #- run: tox -e py -s dist

    # TODO pyinstaller

    - run: pip install twine
    - run: twine upload dist/*
